en:
  æ: ae
  é: e
gr:
  α: a
  β: b
  γ: g
  δ: d
  ε: e
  ζ: z
  η: h
  θ: 8
  ι: i
  κ: k
  λ: l
  μ: m
  ν: n
  ξ: 3
  ο: o
  π: p
  ρ: r
  σ: s
  τ: t
  υ: y
  φ: f
  χ: x
  ψ: ps
  ω: w
  ά: a
  έ: e
  ί: i
  ό: o
  ύ: y
  ή: h
  ώ: w
  ς: s
  ϊ: i
  ΰ: y
  ϋ: y
  ΐ: i
ru:
  а: a
  б: b
  в: v
  г: g
  д: d
  е: e
  ё: io
  ж: j
  з: z
  и: i
  й: yi
  к: k
  л: l
  м: m
  н: n
  о: o
  п: p
  р: r
  с: s
  т: t
  у: u
  ф: f
  х: h
  ц: ts
  ч: ch
  ш: sh
  щ: shch
  ъ: i
  ы: i
  ь: i
  э: ye
  ю: u
  я: ya
  ă: a
  î: i
  ţ: t
  â: a
  ş: s
uk:
  є: ye
  і: i
  ї: yi
  ґ: g
cz:
  č: c
  ď: d
  ě: e
  ň: n
  ř: r
  š: s
  ť: t
  ů: u
  ž: z
pl:
  ą: a
  ć: c
  ę: e
  ł: l
  ń: n
  ó: o
  ś: s
  ź: z
  ż: z
lv:
  ā: a
  č: c
  ē: e
  ģ: g
  ī: i
  ķ: k
  ļ: l
  ņ: n
  š: s
  ū: u
  ž: z
sr:
  а: a
  б: b
  в: v
  г: g
  д: d
  ђ: dj
  е: e
  ж: j
  з: z
  и: i
  ј: j
  к: k
  л: l
  љ: lj
  м: m
  н: n
  њ: nj
  о: o
  п: p
  р: r
  с: s
  т: t
  ћ: c
  у: u
  ф: f
  х: h
  ц: c
  ч: c
  џ: dz
  ш: s
  č: c
  ć: c
  đ: dj
  š: s
  ž: z
tr:
  ç: c
  ğ: g
  ı: i
  İ: I
  ö: o
  ş: s
  ü: u